import type { Unlock } from "../geometry/types";
import { book1Unlocks11To48 } from "./book1ExtendedData";

function withReplay(unlock: Unlock): Unlock {
  if (unlock.replaySteps) {
    return unlock;
  }

  const source = unlock.source ?? unlock.propositionId ?? "Euclid";
  const dependencies = unlock.dependsOn.length > 0 ? unlock.dependsOn.join(", ") : "the initial laws";
  const futureUses = unlock.futureUses.length > 0 ? unlock.futureUses.join(", ") : "future propositions";

  return {
    ...unlock,
    replaySteps: [
      {
        id: "unlock-meaning",
        highlight: [],
        text: `${unlock.name}: ${unlock.description}`,
      },
      {
        id: "unlock-source",
        highlight: [],
        text: `${source} justifies this power. It depends on ${dependencies}.`,
      },
      {
        id: "unlock-future",
        highlight: [],
        text: `${unlock.whatItLetsYouDo ?? "This can now support Euclidean reasoning."} Later use: ${futureUses}.`,
      },
    ],
  };
}

export const primitiveToolUnlocks: Unlock[] = [
  {
    id: "primitive-arrange-triangle",
    unlockType: "primitive-tool",
    name: "Arrange Triangle",
    functionName: "arrangeTriangle",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Digital diagram layer",
    description: "Move and rotate a given triangle without changing its side lengths or angles.",
    whatItLetsYouDo: "Test triangle coincidence directly by sliding and turning a rigid triangle.",
    futureUses: ["I.4"],
  },
  {
    id: "primitive-point-selector",
    unlockType: "primitive-tool",
    name: "Point",
    functionName: "createPoint",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Digital diagram layer",
    description: "Create a point freely on the page, or select an existing point when the click is close.",
    whatItLetsYouDo: "Place auxiliary points, snap to constructed points, and turn flexible drafting into usable Euclidean objects.",
    futureUses: ["All construction propositions"],
  },
  {
    id: "primitive-straightedge",
    unlockType: "primitive-tool",
    name: "Straightedge",
    functionName: "createSegment",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Postulate 1",
    originalStatement: "A straight line may be drawn between two points.",
    description: "Draw a full straight line through two points, creating free defining points when needed.",
    whatItLetsYouDo: "Join given, constructed, snapped, or newly placed points with a line that continues both ways.",
    futureUses: ["I.1", "I.2", "I.3", "I.9", "I.10"],
  },
  {
    id: "primitive-extend-line",
    unlockType: "primitive-tool",
    name: "Extend",
    functionName: "extendSegment",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Postulate 2",
    originalStatement: "A finite straight line may be produced continuously in a straight line.",
    description: "Produce a finite straight-line continuously in a straight line.",
    whatItLetsYouDo: "Extend a known straight-line through one endpoint.",
    futureUses: ["I.2", "I.5", "I.11"],
  },
  {
    id: "primitive-compass",
    unlockType: "primitive-tool",
    name: "Compass",
    functionName: "createCircle",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Postulate 3",
    originalStatement: "A circle may be drawn with any center and radius.",
    description: "Draw a circle from a center point to a radius point, creating either point when needed.",
    whatItLetsYouDo: "Make circles from geometric points without numeric measurement.",
    futureUses: ["I.1", "I.2", "I.3", "I.10"],
  },
  {
    id: "primitive-intersection-selector",
    unlockType: "primitive-tool",
    name: "Intersection Selector",
    functionName: "createPointAtIntersection",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Digital Euclidean diagram control",
    description: "Create a point where constructed objects intersect.",
    whatItLetsYouDo: "Turn a valid crossing into a usable point.",
    futureUses: ["I.1", "I.2", "I.3", "I.10"],
  },
];

export const initialLogicUnlocks: Unlock[] = [
  {
    id: "logic-postulate-1",
    unlockType: "logic-rule",
    name: "Straight Line",
    functionName: "postulateStraightLineBetweenPoints",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Postulate 1",
    description: "A straight line may be drawn between two points.",
    futureUses: ["I.1", "I.2"],
  },
  {
    id: "logic-postulate-3",
    unlockType: "logic-rule",
    name: "Circle",
    functionName: "postulateCircleWithCenterAndRadius",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Postulate 3",
    description: "A circle may be drawn with any center and radius.",
    futureUses: ["I.1", "I.2", "I.3"],
  },
  {
    id: "logic-definition-1-15",
    unlockType: "logic-rule",
    name: "Radius Equality",
    functionName: "circleRadiusEquality",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Definition 1.15",
    description: "All radii of the same circle are equal.",
    futureUses: ["I.1", "I.2", "I.3"],
  },
  {
    id: "logic-common-notion-1",
    unlockType: "logic-rule",
    name: "Equality Transfer",
    functionName: "commonNotionEqualityTransfer",
    visibleToPlayer: true,
    dependsOn: [],
    source: "Common Notion 1",
    description: "Things equal to the same thing are equal to one another.",
    futureUses: ["I.1", "I.2", "I.3"],
  },
];

export const hiddenAxiomUnlocks: Unlock[] = [
  {
    id: "logic-common-notion-3",
    unlockType: "logic-rule",
    name: "Subtract Equals",
    functionName: "commonNotionSubtractEquals",
    visibleToPlayer: false,
    dependsOn: [],
    source: "Common Notion 3",
    description: "If equals are subtracted from equals, the remainders are equal.",
    futureUses: ["I.2", "I.5"],
  },
  {
    id: "logic-common-notion-4",
    unlockType: "logic-rule",
    name: "Coinciding Things Are Equal",
    functionName: "commonNotionCoincidence",
    visibleToPlayer: false,
    dependsOn: [],
    source: "Common Notion 4",
    description: "Things which coincide with one another are equal to one another.",
    futureUses: ["I.4", "I.8"],
  },
  {
    id: "logic-common-notion-5",
    unlockType: "logic-rule",
    name: "Whole Greater Than Part",
    functionName: "commonNotionWholeGreaterThanPart",
    visibleToPlayer: false,
    dependsOn: [],
    source: "Common Notion 5",
    description: "The whole is greater than the part.",
    futureUses: ["I.6"],
  },
];

export const propositionUnlocks: Unlock[] = [
  {
    id: "unlock-I.1-equilateral",
    propositionId: "I.1",
    unlockType: "theorem-action",
    name: "Build Equilateral Triangle",
    functionName: "constructEquilateralTriangleOnSegment",
    visibleToPlayer: true,
    dependsOn: ["primitive-straightedge", "primitive-compass", "primitive-intersection-selector"],
    source: "Euclid I.1",
    originalStatement: "To construct an equilateral triangle on a given finite straight-line.",
    description: "You proved that an equilateral triangle can be constructed on a given segment.",
    whatItLetsYouDo: "Select a segment and construct an equilateral triangle on it as an earned theorem-action.",
    futureUses: ["I.2", "I.9", "I.10"],
  },
  {
    id: "unlock-I.2-transfer-length",
    propositionId: "I.2",
    unlockType: "theorem-action",
    name: "Transfer Length to Point",
    functionName: "transferSegmentToPoint",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.1-equilateral"],
    source: "Euclid I.2",
    originalStatement: "To place a straight-line equal to a given straight-line at a given point.",
    description: "Length transfer is earned here. It is not a primitive copy tool.",
    whatItLetsYouDo: "Transfer a given segment length so it starts at a chosen point.",
    futureUses: ["I.3", "I.11", "I.12"],
  },
  {
    id: "unlock-I.2-set-compass-width",
    propositionId: "I.2",
    unlockType: "theorem-action",
    name: "Copy Length",
    functionName: "createCircleWithTransferredRadius",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.2-transfer-length", "primitive-compass"],
    source: "Euclid I.2",
    originalStatement: "To place a straight-line equal to a given straight-line at a given point.",
    description: "Copy a known length from a chosen start point onto a target line or ray.",
    whatItLetsYouDo: "Place a point on a chosen line or ray so the new segment equals the source length.",
    futureUses: ["I.3", "I.9", "I.10", "later circle and segment transfer constructions"],
  },
  {
    id: "unlock-I.3-cut-off",
    propositionId: "I.3",
    unlockType: "theorem-action",
    name: "Copy Length",
    functionName: "cutOffEqualSegment",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.2-transfer-length"],
    source: "Euclid I.3",
    originalStatement: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
    description: "Copy a length from a start point onto a chosen line or ray.",
    whatItLetsYouDo: "Place or cut off an equal segment with the unified Copy Length tool.",
    futureUses: ["I.5", "I.6", "I.9"],
  },
  {
    id: "unlock-I.4-sas",
    propositionId: "I.4",
    unlockType: "theorem-action",
    name: "SAS",
    functionName: "applySASCongruence",
    visibleToPlayer: true,
    dependsOn: ["logic-common-notion-4"],
    source: "Side-Angle-Side",
    description: "Use two corresponding sides and the included angle to prove two triangles congruent.",
    whatItLetsYouDo: "Use a side, the included angle, and a second side as a proof theorem.",
    futureUses: ["I.5", "I.6", "I.10"],
  },
  {
    id: "unlock-I.5-isosceles-base-angles",
    propositionId: "I.5",
    unlockType: "logic-rule",
    name: "Isosceles Base Angles",
    functionName: "applyIsoscelesBaseAngles",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.3-cut-off", "unlock-I.4-sas"],
    source: "Euclid I.5",
    description: "Equal sides in an isosceles triangle imply equal base angles.",
    whatItLetsYouDo: "Use equal sides to infer equal angles in proofs.",
    futureUses: ["I.7"],
  },
  {
    id: "unlock-I.6-converse-isosceles",
    propositionId: "I.6",
    unlockType: "logic-rule",
    name: "Equal Angles, Equal Sides",
    functionName: "applyConverseIsosceles",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.3-cut-off", "unlock-I.4-sas", "logic-common-notion-5"],
    source: "Euclid I.6",
    description: "Equal angles in a triangle imply equal opposite sides.",
    whatItLetsYouDo: "Use equal angles to infer side equality.",
    futureUses: ["Later triangle proofs"],
  },
  {
    id: "unlock-I.7-two-distance-uniqueness",
    propositionId: "I.7",
    unlockType: "constraint-rule",
    name: "Unique Point from Two Distances",
    functionName: "applyTwoDistancePointUniqueness",
    visibleToPlayer: false,
    dependsOn: ["unlock-I.5-isosceles-base-angles"],
    source: "Euclid I.7",
    description: "Two fixed distances from the same endpoints determine only one point on the same side.",
    whatItLetsYouDo: "Engine constraint for uniqueness and ambiguity resolution.",
    futureUses: ["I.8"],
  },
  {
    id: "unlock-I.8-sss",
    propositionId: "I.8",
    unlockType: "theorem-action",
    name: "SSS",
    functionName: "applySSSCongruence",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.7-two-distance-uniqueness"],
    source: "Euclid I.8",
    description: "Use three corresponding sides to prove two triangles congruent.",
    whatItLetsYouDo: "Reason from side-side-side congruence.",
    futureUses: ["I.9"],
  },
  {
    id: "unlock-I.9-angle-bisector",
    propositionId: "I.9",
    unlockType: "theorem-action",
    name: "Bisect Angle",
    functionName: "bisectAngle",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.1-equilateral", "unlock-I.3-cut-off", "unlock-I.8-sss"],
    source: "Euclid I.9",
    description: "You proved how to cut a rectilinear angle in half.",
    whatItLetsYouDo: "Construct an angle bisector as an earned theorem-action.",
    futureUses: ["I.10", "I.11"],
  },
  {
    id: "unlock-I.10-segment-bisector",
    propositionId: "I.10",
    unlockType: "theorem-action",
    name: "Bisect Segment / Find Midpoint",
    functionName: "bisectSegment",
    visibleToPlayer: true,
    dependsOn: ["unlock-I.1-equilateral", "unlock-I.4-sas", "unlock-I.9-angle-bisector"],
    source: "Euclid I.10",
    description: "You proved how to cut a finite straight-line in half.",
    whatItLetsYouDo: "Find a segment midpoint as an earned theorem-action.",
    futureUses: ["I.11", "I.12"],
  },
];

export const semanticTokenUnlocks: Unlock[] = [
  {
    id: "token-equilateral-triangle",
    propositionId: "I.1",
    unlockType: "semantic-token",
    name: "EquilateralTriangle",
    functionName: "semanticTokenEquilateralTriangle",
    visibleToPlayer: false,
    dependsOn: ["unlock-I.1-equilateral"],
    description: "Semantic token for triangles with three equal sides.",
    futureUses: ["I.2", "I.10"],
  },
  {
    id: "token-transferred-length",
    propositionId: "I.2",
    unlockType: "semantic-token",
    name: "TransferredLength",
    functionName: "semanticTokenTransferredLength",
    visibleToPlayer: false,
    dependsOn: ["unlock-I.2-transfer-length"],
    description: "Semantic token for a segment placed equal to a given segment.",
    futureUses: ["I.3"],
  },
  {
    id: "token-cut-off-segment",
    propositionId: "I.3",
    unlockType: "semantic-token",
    name: "CutOffSegment",
    functionName: "semanticTokenCutOffSegment",
    visibleToPlayer: false,
    dependsOn: ["unlock-I.3-cut-off"],
    description: "Semantic token for cutting a longer segment by a shorter length.",
    futureUses: ["I.5", "I.6"],
  },
];

const unlockDefinitions: Unlock[] = [
  ...primitiveToolUnlocks,
  ...initialLogicUnlocks,
  ...hiddenAxiomUnlocks,
  ...propositionUnlocks,
  ...book1Unlocks11To48,
  ...semanticTokenUnlocks,
];

export const unlocks: Unlock[] = unlockDefinitions.map(withReplay);

export const unlockById = new Map(unlocks.map((unlock) => [unlock.id, unlock]));
