import type { Proposition } from "../geometry/types";
import { book1Prop1 } from "./book1prop1";

// Proposition text follows the user-supplied Richard Fitzpatrick translation PDF.
export const book1Prop3: Proposition = {
  id: "I.3",
  book: "Book I",
  number: 3,
  title: "Cut Off an Equal Straight-Line",
  subtitle: "Build the Elements",
  playerGoal: "Cut off from the greater straight-line AB a part equal to the lesser straight-line CD.",
  originalStatement: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
  instruction: "Use Copy Length: take CD as the source length, start at A, and place E on AB so AE = CD.",
  initialObjects: [
    {
      id: "A",
      type: "point",
      x: 220,
      y: 340,
      label: "A",
      fixed: true,
      createdBy: "given",
      color: "red",
    },
    {
      id: "B",
      type: "point",
      x: 700,
      y: 340,
      label: "B",
      fixed: true,
      createdBy: "given",
      color: "blue",
    },
    {
      id: "C",
      type: "point",
      x: 260,
      y: 160,
      label: "C",
      fixed: true,
      createdBy: "given",
      color: "gold",
    },
    {
      id: "D",
      type: "point",
      x: 410,
      y: 160,
      label: "D",
      fixed: true,
      createdBy: "given",
      color: "gold",
    },
    {
      id: "AB",
      type: "segment",
      p1: "A",
      p2: "B",
      label: "AB",
      color: "black",
      given: true,
      source: "given",
    },
    {
      id: "CD",
      type: "segment",
      p1: "C",
      p2: "D",
      label: "CD",
      color: "black",
      given: true,
      source: "given",
    },
  ],
  allowedTools: ["point", "straightedge", "compass", "compass-transfer", "intersection"],
  pointLabelSequence: ["P", "E", "F", "G", "H", "K", "L", "M", "N", "O", "Q", "R", "S", "T"],
  nextPropositionId: "I.4",
  lawSections: book1Prop1.lawSections,
  replaySteps: [
    {
      id: "given",
      highlight: ["segmentAB", "segmentCD", "pointA", "pointB", "pointC", "pointD"],
      text: "Let AB and CD be the given unequal straight-lines, AB the greater.",
    },
    {
      id: "place-copy",
      highlight: ["segmentCD", "pointA"],
      text: "Use Copy Length with CD as the source length and A as the target start point.",
    },
    {
      id: "circle",
      highlight: ["segmentAB", "segmentCD", "pointA"],
      text: "Choose AB as the target line for the copied length.",
    },
    {
      id: "cut",
      highlight: ["segmentAB", "pointE"],
      text: "Let E be the point placed on the greater straight-line AB.",
    },
    {
      id: "radius",
      highlight: ["segmentAE", "segmentCD", "pointA", "pointE"],
      text: "Copy Length places E so that AE = CD. [Prop. I.2-I.3]",
    },
    {
      id: "common-notion",
      highlight: ["segmentAE", "segmentCD"],
      text: "Thus the segment cut from AB equals the lesser given straight-line CD.",
    },
    {
      id: "conclusion",
      highlight: ["segmentAE", "segmentAB", "segmentCD", "pointA", "pointE"],
      text: "Thus AE, equal to the lesser CD, has been cut off from AB.",
    },
  ],
};
