import type { Proposition } from "../geometry/types";
import { book1Prop1 } from "./book1prop1";

// Proposition text follows the user-supplied Richard Fitzpatrick translation PDF.
export const book1Prop3: Proposition = {
  id: "I.3",
  book: "Book I",
  number: 3,
  title: "Cut Off an Equal Straight-Line",
  subtitle: "Build the Elements",
  playerGoal: "Cut off from the greater straight-line AB a part equal to the lesser straight-line CD.",
  originalStatement: "For two given unequal straight-lines, to cut off from the greater a straight-line equal to the lesser.",
  instruction: "Set the compass width to CD, draw from center A, then cut that length from AB.",
  initialObjects: [
    {
      id: "A",
      type: "point",
      x: 220,
      y: 340,
      label: "A",
      fixed: true,
      createdBy: "given",
      color: "red",
    },
    {
      id: "B",
      type: "point",
      x: 700,
      y: 340,
      label: "B",
      fixed: true,
      createdBy: "given",
      color: "blue",
    },
    {
      id: "C",
      type: "point",
      x: 260,
      y: 160,
      label: "C",
      fixed: true,
      createdBy: "given",
      color: "gold",
    },
    {
      id: "D",
      type: "point",
      x: 410,
      y: 160,
      label: "D",
      fixed: true,
      createdBy: "given",
      color: "gold",
    },
    {
      id: "AB",
      type: "segment",
      p1: "A",
      p2: "B",
      label: "AB",
      color: "black",
      given: true,
      source: "given",
    },
    {
      id: "CD",
      type: "segment",
      p1: "C",
      p2: "D",
      label: "CD",
      color: "black",
      given: true,
      source: "given",
    },
  ],
  allowedTools: ["point", "straightedge", "extend", "compass", "intersection"],
  pointLabelSequence: ["P", "E", "F", "G", "H", "K", "L", "M", "N", "O", "Q", "R", "S", "T"],
  lawSections: book1Prop1.lawSections,
  replaySteps: [
    {
      id: "given",
      highlight: ["segmentAB", "segmentCD", "pointA", "pointB", "pointC", "pointD"],
      text: "Let AB and CD be the given unequal straight-lines, AB the greater.",
    },
    {
      id: "place-copy",
      highlight: ["segmentCD", "pointA"],
      text: "Set the compass width to CD; this transfer is justified by Proposition I.2.",
    },
    {
      id: "circle",
      highlight: ["circleA", "segmentCD", "pointA"],
      text: "Draw a circle with center A using that same width. [Post. 3]",
    },
    {
      id: "cut",
      highlight: ["circleA", "segmentAB", "pointE"],
      text: "Let E be where the circle cuts the greater straight-line AB.",
    },
    {
      id: "radius",
      highlight: ["circleA", "segmentAE", "segmentCD", "pointA", "pointE"],
      text: "Every point on this circle is distance CD from A; hence AE = CD. [Def. 1.15, I.2]",
    },
    {
      id: "common-notion",
      highlight: ["segmentAE", "segmentCD"],
      text: "Thus the segment cut from AB equals the lesser given straight-line CD.",
    },
    {
      id: "conclusion",
      highlight: ["segmentAE", "segmentAB", "segmentCD", "pointA", "pointE"],
      text: "Thus AE, equal to the lesser CD, has been cut off from AB.",
    },
  ],
};
